version: "2"
plugins:
  eslint:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
  identical-code:
    enabled: true
    
exclude_patterns:
  - "node_modules/"
  - "**/node_modules/"
  - "UI/"
  - "CLIENT/"
  - "dist/"
  - script/
  - "**/specs/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "SERVER/spec/*"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/src/middleware/validation/**"
  - "**/src/middleware/validation.js"
  