language: node_js
node_js:
    - "10.15.3"
install:
    - npm install
env:
  global:
   - CC_TEST_REPORTER_ID=608827752756cf288300846cf633509fac5750c70568f08f32ba3285e1c8564c

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coveralls

notifications:
  email: false