version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      NODE_ENV: "development"
      PRODUCTION: 'true'
      PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    user: postgres
    ports:
      - "${HOST_PORT}:${DB_PORT}"
    environment: 
      POSTGRES_DATABASE: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: